name: 'volta setup'
description: 'configures volta, node, yarn and caches'
runs:
  using: 'composite'
  steps:
    - name: setup-volta vars
      id: vars
      shell: bash
      run: python3 -uS ${{ github.action_path }}/bin/setup-volta vars

    - name: cache volta+node+yarn
      id: cache
      uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7  # v3.0.11
      with:
        path: ${{ steps.vars.outputs.volta-dir }}
        key: ${{ steps.vars.outputs.cache-key }}

    - name: install volta+node+yarn
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: python3 -uS ${{ github.action_path }}/bin/setup-volta install

    - name: yarn cache dir
      id: yarn
      shell: bash
      run: python3 -uS ${{ github.action_path }}/bin/setup-volta yarn-cache-dir

    - name: cache yarn
      uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7  # v3.0.11
      with:
        path: ${{ steps.yarn.outputs.cache-dir }}
        key: ${{ steps.vars.outputs.cache-key }}-${{ hashFiles('**/yarn.lock') }}
